### ISSUE TITLE
in section 3.5, quiz, hint link is invalid

### ISSUE THREAD

**Issue by lewiswilliam** [redislabs-training/ru203#10]
In section 3.5 quiz, Hint: The documentation contains a list of valid [APPLY expressions](https://oss.redislabs.com/redisearch/Aggregations/#apply_expressions).

This link is a 404 currently and does not exist.

Should be replaced with: https://redis.io/docs/stack/search/reference/aggregations/#apply-expressions

**Comment by simonprickett** [comment]
@lewiswilliam sorry for the slow response, just seen this... I'll get it fixed. Thank you, hope you enjoyed the course.

**Comment by simonprickett** [comment]
@lewiswilliam thanks I've updated the course materials now.
