### ISSUE TITLE
Amend the `docker-compose.yml` file for this course to use the Redis Stack container and re-test

### ISSUE THREAD

**Issue by simonprickett** [redislabs-training/ru203#11]
This course currently uses an older version of the RediSearch container in its `docker-compose.yml` file.

Amend the `docker-compose.yml` file for this course to use the Redis Stack container and test that data loading process, the index generation commands and sample query in `README.md` all still work.

Don't rename the container - leave it named `redis-search`.

This is part of our participation in Hacktoberfest 2022. Learn how to complete this issue here: https://redis.io/community/hacktoberfest/

Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

If you're interested in taking this issue on, please mention @simonprickett and @SuzeShardlow in the comments and ask to be assigned.

**Comment by simonprickett** [comment]
@Mephalich thanks for the interest... in the interests of wide community involvement, one of our rules is:

> To be fair to other contributors, only claim one issue at a time.

https://redis.io/community/hacktoberfest/

Thanks!

Redis Devrel Team.

**Comment by Mephalich** [comment]
Oops, my bad. Was too excited. :)

**Comment by AsyncDeveloper245** [comment]
Thank you @simonprickett  Looking to learning and contributing to the community.
